### ISSUE TITLE
Cig duplicati

### ISSUE THREAD

**Issue by frenier** [provinciadicremona/AVCP-Xml#13]
Ciao,
ho notato questo comportamento:
due utenti diversi inseriscono la stessa gara, il programma permette la registrazione dello stesso cig senza dare segnalazioni.
Non ho idea se sia un comportamento voluto o meno, a me pare un errore.

**Comment by ClaudioRoncaglio** [comment]
Ciao,
l'inserimento di più gare con lo stesso CIG è un comportamento perfettamente legale per ANAC e viene usato in molti casi dalle amministrazioni:

1.  determine a contrarre 
2. determine con più aggiudicatari (ad esempio se con la stessa determina per un buffet aggiudichi ad una ditta il catering e ad un'altra le pulizie, ANAC si aspetta di trovare due lotti nell'XML)
