### ISSUE TITLE
Webservices

### ISSUE THREAD

**Issue by frenier** [provinciadicremona/AVCP-Xml#14]
Ciao,
sto' cercando di pilotare la tabella avcp_lotto da un applicativo esterno.
precisamente mi piacerebbe aggiornare l' importoSommeLiquidate interrogandolo per id o per cig.
Avete qualcosa di disponibile come ws tramite chiamata REST.
Io sono riuscito a farlo tramite un Linked server su MSSQL ma l'applicativo ha un vincolo di programmazione che non permette di usare l'istruzione UPDATE e mi permette di eseguire istruzioni REST quindi vorrei girarci attorno.

**Comment by ClaudioRoncaglio** [comment]
Di pronto non abbiamo niente ma volendo si può implementare facilmente.

Io ti consiglierei di mettere uno script php nella cartella app/webServices che faccia quello che desideri , basta ricordarsi di includere all'inizio il file config.php (prova a dare un'occhiata a come funzionano quelli presenti tanto per farti un'idea). 

Se opti per una soluzione di questo tipo, ovviamente **ti apri a grossi problemi di sicurezza**, soprattutto se l'applicazione è direttamente accessibile da internet e non in una rete locale. In questo caso sarebbe meglio aggiungere un token e ricordarsi di accedere sempre in https (io però non so se ci dormirei tranquillo) :skull_and_crossbones:
