### ISSUE TITLE
Nuove voci per "scelta contraente" (novembre 2019)

### ISSUE THREAD

**Issue by alberto-dev** [provinciadicremona/AVCP-Xml#17]
Buongiorno, a quanto sembra ci sono nuovamente degli aggiornamenti per la "scelta contraente" http://dati.anticorruzione.it/schema/TypesL190.xsd. Non solo hanno aggiunto delle voci, ma hanno anche cambiato il testo di alcune di quelle già esistenti. Non so se questo nuovo elenco sia già ufficiale, ma credo poi vada aggiornato xsd e voci in tabella, oltre forse a dover aggiornare il testo delle voci pregresse già inserite con le vecchie descrizioni.
Ci sono già in programma degli aggiornamenti applicativi su questo tema?
Grazie

**Comment by ClaudioRoncaglio** [comment]
Innanzitutto grazie per la segnalazione. 
Ho cercato nel sito dell'anticorruzione e sembra che tutte queste nuove specifiche, [introdotte il 4 novembre,](http://www.anticorruzione.it/portal/public/classic/Servizi/ServiziOnline/DichiarazioneAdempLegge190) cioè ieri, e non  ancora comunicate con una news, dovranno essere usate per la generazione dell'xml relativo al 2019. 
Vista la situazione, mi ritrovo costretto a rimandare gli altri lavori che sto seguendo per dedicarmi all'aggiornamento in tempi brevissimi dell'applicativo, anche perché la brillante idea di modificare le voci già esistenti (**a novembre!**), mi costringe ad aggiungere, nella fase di update del programma, la modifica dei lotti già inseriti.

**Comment by alberto-dev** [comment]
Grazie mille, immagino servirà anche un qualche script di update del pregresso.
Se dovesse servire qualche aiuto... premetto però che non ho una gran conoscenza dell'applicativo e della struttura del database.

**Comment by ClaudioRoncaglio** [comment]
> Grazie mille, immagino servirà anche un qualche script di update del pregresso.
Assolutamente sì, per fortuna nel branch dev avevo iniziato la gestione degli aggiornamenti in base alla versione di partenza.

Per l'offerta di aiuto la ringrazio, ma prima è meglio che mi chiarisca bene le idee sulla maniera più pulita possibile di affrontare la cosa, anche perché se qualcosa va storto passerò gennaio a rispondere alla richieste di assistenza  degli altri enti ;-)

**Comment by ClaudioRoncaglio** [comment]
E niente, manco le citazioni giuste riesco a fare....

**Comment by alberto-dev** [comment]
Buon lavoro intanto, se servisse qualcosa abbiamo questa issue aperta.
Grazie

**Comment by alberto-dev** [comment]
Aggiungo: se dovesse servire qualche test extra, se pubblichi le modifiche su un ramo separato (prima di riportarle in master), posso fare delle prove con le installazioni che abbiamo qui per vedere se l'aggiornamento va a buon fine.
Grazie

**Comment by ClaudioRoncaglio** [comment]
Grazie, le assicuro che qualcuno che ci aiuti nei test fa sempre comodo.
Intanto il mio collega @giannibassiniprovincia ha aperto un ticket con l'anticorruzione per capire se le modifiche devono essere applicate anche al 2019, perché nel sito loro scrivono:

> Si precisa che i file XML da pubblicare per gli adempimenti del 2020 e successivi, dovranno essere realizzati utilizzando solo l’ultima versione dei file XSD pubblicati nella successiva sezione ‘Specifiche XSD’.

Tutto sta a capire se per _"adempimenti del 2020"_ considerino l'anno rilevato (e saremmo salvi) o l'anno dell'invio. 
Appena avremo risposta le farò sapere.

**Comment by ClaudioRoncaglio** [comment]
Le modifiche introdotte dovranno essere usate anche per rendicontare l'attività dell'anno 2019.
Sto finendo le modifiche al programma.

**Comment by alberto-dev** [comment]
Grazie.
Per l'aggiornamento del pregresso ci sarà un apposito script da lanciare direttamente a db o qualche altro tipo di procedura?
Se occorre un test extra fatemi sapere quando il ramo di dev (che se ho capito bene sta accogliendo le attuali modifiche) è pronto, così posso fare delle prove qui da noi e farvi sapere l'esito

**Comment by ClaudioRoncaglio** [comment]
Prego!
Non ci sarà nessuno script da lanciare: dalla prossima release tutti gli aggiornamenti verranno fatti in automatico alla prima visualizzazione della schermata di login.
Le modifiche dell'ANAC sono già finite e funzionanti, adesso sto finendo questo automatismo sugli aggiornamenti, che sarà sempre attivo anche nelle prossime versioni.
Mi dò tempo un paio di giorni per finirlo e fare un po' di test e poi lo pubblicherò.

**Comment by dgardina** [comment]
Buongiorno @ClaudioRoncaglio .. qualche novità in merito ai test e alla data di rilascio dell'aggiornamento? Grazie!!

**Comment by ClaudioRoncaglio** [comment]
Buongiorno @dgardina , gli aggiornamenti sono finiti e funzionanti.
 
Sto finendo di commentare il codice e di ripulirlo un po'. Farò ancora i test dopo la ripulitura, giusto per essere sicuro di non aver lasciato qualche punto e virgola vagante e poi passo a scrivere le istruzioni per l'aggiornamento.

Se vuole provare a fare un test, può usare la versione sul branch dev. 

Se tutto va bene, alla prima visualizzazione della pagina di login le apparirà il messaggio di conferma "Aggiornamento dalla versione 0.7.* alla versione 0.8.0 del programma terminato", altrimenti il programma si inchioderà con un codice di errore.

Mi raccomando, faccia una copia del db!!! :smile:

**Comment by ClaudioRoncaglio** [comment]
Dimenticavo: se no esplode niente la rilascerò lunedì, preferibilmente in mattinata.
