### ISSUE TITLE
Tipologie di scelta contraente (aggiornamento a v. 0.8.8)

### ISSUE THREAD

**Issue by dgardina** [provinciadicremona/AVCP-Xml#22]
Le tipologie di scelta contraente sono cambiate nel nuovo XSD fornito da ANAC..

03-PROCEDURA NEGOZIATA PREVIA PUBBLICAZIONE DEL BANDO
è diventata
03-PROCEDURA NEGOZIATA PREVIA PUBBLICAZIONE

04-PROCEDURA NEGOZIATA SENZA PREVIA PUBBLICAZIONE DEL BANDO
è diventata
04-PROCEDURA NEGOZIATA SENZA PREVIA PUBBLICAZIONE

06-PROCEDURA NEGOZIATA SENZA PREVIA INDIZIONE DI GARA ART. 221 D.LGS. 163/2006
è diventata
06-PROCEDURA NEGOZIATA SENZA PREVIA INDIZIONE DI GARA (SETTORI SPECIALI)

17-AFFIDAMENTO DIRETTO EX ART. 5 DELLA LEGGE N.381/91
è diventata
17-AFFIDAMENTO DIRETTO EX ART. 5 DELLA LEGGE 381/91

22-PROCEDURA NEGOZIATA DERIVANTE DA AVVISI CON CUI SI INDICE LA GARA
è diventata
22-PROCEDURA NEGOZIATA CON PREVIA INDIZIONE DI GARA (SETTORI SPECIALI)

23-AFFIDAMENTO IN ECONOMIA - AFFIDAMENTO DIRETTO
è diventata
23-AFFIDAMENTO DIRETTO

Segnalo che lo script non fa la modifica in automatico, per cui ho dovuto cambiare a mano (massivamente) il valore nel SQL del dump e reimportarlo..

**Comment by dgardina** [comment]
Non sarebbe possibile (consigliabile) utilizzare una tabella esterna per la scelta contraente, limitando la presenza del solo codice/id ("01", "02", ...) nella tabella dei lotti?

**Comment by dgardina** [comment]
Segnalo, tra l'altro, che nella pagina di inserimento di un nuovo lotto si vede la vecchia lista di scelta contraente (con i valori fino a 31 e non a 38 e i label errati/vecchi).

**Comment by ProvinciaCremona** [comment]
Mi viene il dubbio che abbia collegato il vecchio db al nuovo programma, o che l'aggiornamento sia fallito.


-----------------------------------------
Claudio Roncaglio
Ufficio per le Relazioni con il Pubblico
della Provincia di Cremona 
C.so Vittorio Emanuele II,17
tel. +39 0372 406247 fax +39 0372 406301
-----------------------------------------

----- Messaggio originale -----
Da: "Diego Gardina" <notifications@github.com>
A: "provinciadicremona" <AVCP-Xml@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Inviato: Martedì, 10 dicembre 2019 12:22:10
Oggetto: Re: [provinciadicremona/AVCP-Xml] Tipologie di scelta contraente (#22)

Segnalo, tra l'altro, che nella pagina di inserimento di un nuovo lotto si vede la vecchia lista di scelta contraente (con i valori fino a 31 e non a 38 e i label errati/vecchi).

**Comment by dgardina** [comment]
Prima di mettere in produzione il tutto sto facendo dei test in locale, mi sono quindi scaricato i dati e fatto un dump del db di ogni istanza.. In questa in particolare l'aggiornamento mi ha dato esito positivo (stando al messaggio nella pagina di login).
I dati del config.php sono corretti (server localhost, schema + username + password corretti).. tutto può essere, ma ho una buona percentuale di certezza di aver fatto quanto indicato dalla guida..

**Comment by dgardina** [comment]
Ho verificato un'altra istanza (che ha dato errore in aggiornamento) ed il problema è presente anche lì.. errore di validazione perché il campo non è aggiornato e valori solo fino a 31 durante l'inserimento di un nuovo lotto..

**Comment by dgardina** [comment]
Vedo ora che (lo script?) ha aggiornato il campo "ruolo" della tabella avcp_sceltacontraentetype ma NON il campo "sceltaContraente" della tabella avcp_lotto..

**Comment by ProvinciaCremona** [comment]
Lanci queste query:

UPDATE `avcp_lotto` SET `sceltaContraente` = '03-PROCEDURA NEGOZIATA PREVIA PUBBLICAZIONE' WHERE `sceltaContraente` LIKE '03-%';
UPDATE `avcp_lotto` SET `sceltaContraente` = '04-PROCEDURA NEGOZIATA SENZA PREVIA PUBBLICAZIONE' WHERE `sceltaContraente` LIKE '04-%';
UPDATE `avcp_lotto` SET `sceltaContraente` = '06-PROCEDURA NEGOZIATA SENZA PREVIA INDIZIONE DI GARA (SETTORI SPECIALI)' WHERE `sceltaContraente` LIKE '06-%';
UPDATE `avcp_lotto` SET `sceltaContraente` = '17-AFFIDAMENTO DIRETTO EX ART. 5 DELLA LEGGE 381/91' WHERE `sceltaContraente` LIKE '17-%';
UPDATE `avcp_lotto` SET `sceltaContraente` = '22-PROCEDURA NEGOZIATA CON PREVIA INDIZIONE DI GARA (SETTORI SPECIALI)' WHERE `sceltaContraente` LIKE '22-%';
UPDATE `avcp_lotto` SET `sceltaContraente` = '23-AFFIDAMENTO DIRETTO' WHERE `sceltaContraente` LIKE '23-%';
UPDATE `avcp_lotto` SET `sceltaContraente` = '27-CONFRONTO COMPETITIVO IN ADESIONE AD ACCORDO QUADRO/CONVENZIONE' WHERE `sceltaContraente` LIKE '27-%';

Dovrebbero risolvere.





-----------------------------------------
Claudio Roncaglio
Ufficio per le Relazioni con il Pubblico
della Provincia di Cremona 
C.so Vittorio Emanuele II,17
tel. +39 0372 406247 fax +39 0372 406301
-----------------------------------------

----- Messaggio originale -----
Da: "Diego Gardina" <notifications@github.com>
A: "provinciadicremona" <AVCP-Xml@noreply.github.com>
Cc: "ProvinciaCremona" <github@provincia.cremona.it>, "Comment" <comment@noreply.github.com>
Inviato: Martedì, 10 dicembre 2019 13:07:25
Oggetto: Re: [provinciadicremona/AVCP-Xml] Tipologie di scelta contraente (aggiornamento a v. 0.8.8) (#22)

Vedo ora che (lo script?) ha aggiornato il campo "ruolo" della tabella avcp_sceltacontraentetype ma NON il campo "sceltaContraente" della tabella avcp_lotto..

**Comment by dgardina** [comment]
Certo, questo sicuramente, ma avevo già risolto in fase di analisi.. ;-) Il problema è capire perché non me l'ha fatto lo script in fase di aggiornamento.. :-(

**Comment by ClaudioRoncaglio** [comment]
Sinceramente lo script di aggiornamento le dovrebbe fare, quelle che le ho
mandato le ho prese da lì e in tutte le mie installazioni sono state
eseguite correttamente. Indagherò per capire perché non sono state eseguite.

Il mar 10 dic 2019, 12:17 Diego Gardina <notifications@github.com> ha
scritto:
