### ISSUE TITLE
Aggiornamento mancante su scelta contraente (cod. 25)

### ISSUE THREAD

**Issue by alberto-dev** [provinciadicremona/AVCP-Xml#23]
Salve, durante l'aggiornamento delle nostre installazioni ci siamo accorti che forse manca l'aggiornamento di una delle scelte contraenti, nel relativo script di migrazione del database.
Il valore della scelta 25 era:

> 25-AFFIDAMENTO DIRETTO A SOCIETA' RAGGRUPPATE/CONSORZIATE O CONTROLLATE NELLE CONCESSIONI DI LL.PP

Mentre ora è:

> 25-AFFIDAMENTO DIRETTO A SOCIETA' RAGGRUPPATE/CONSORZIATE O CONTROLLATE NELLE CONCESSIONI E NEI PARTENARIATI

Ho preso i valori dal file xml con le definizioni. Lo script inoltre va ad aggiornare il codice 27, che invece non è cambiato.
Grazie

**Comment by ClaudioRoncaglio** [comment]
Ha perfettamente ragione, mi devo essere confuso mentre elencavo le voci da cambiare.
Correggo subito e rilascio una nuova versione.
Grazie della segnalazione :+1:

**Comment by alberto-dev** [comment]
Grazie mille. Abbiamo fatto un primo aggiornamento di release, e a parte questo non ne abbiamo trovato altri. Se rilascia la patch a breve abbiamo la possibilità di riprovarla su altre installazioni, per avere un ritorno.

**Comment by ClaudioRoncaglio** [comment]
La nuova versione è quasi finita, tra qualche minuto la pubblico.

**Comment by ClaudioRoncaglio** [comment]
Ok, nuova release caricata su github.

**Comment by ClaudioRoncaglio** [comment]
Coome non detto, ho dimenticato di modificare una cosa, non la installate

**Comment by ClaudioRoncaglio** [comment]
Ok, rilasciata come 0.8.10
