### ISSUE TITLE
[BUG] AGGIORNAMENTO NON ANDATO A BUON FINE DA 0.7.1 A 0.8.11

### ISSUE THREAD

**Issue by giampieroguzzio** [provinciadicremona/AVCP-Xml#24]
Ho aggiornato secodo la precedura indicata e ricevo questo errore:
Errore nella CREATE di updateViewDitte. Aggiornamento fallito!

**Comment by ClaudioRoncaglio** [comment]
Salve, il problema è legato ai permessi dell'utente del db usato dal
programma. Deve assicurarsi che abbia anche i permessi per le DROP. Di
solito è preferibile dargli tutti i GRANT su quel db.  Aggiusti queste cose
e ripeta la procedura con un db "pulito".

Il dom 29 dic 2019, 09:21 giampieroguzzio <notifications@github.com> ha
scritto:
