### ISSUE TITLE
Errore controllo versione

### ISSUE THREAD

**Issue by herald-si** [provinciadicremona/AVCP-Xml#25]
Per come è gestito ora il controllo quando la versione di arrivo è >= 10 e quella di partenza è > 1 il non viene aggiornato il database.
Ad esempio:
se versione di `partenza = 0.8.3` e ultima `versione = 0.8.11` il controllo 
`partenza < ultima` restituisce erroneamente `false` perché si ferma a 3<1
utilizzando la versione 0.8.9 viene infatti aggiornato il db correttamente

**Comment by ClaudioRoncaglio** [comment]
Me ne ero accorto e ho corretto l'errore in [questo commit](https://github.com/provinciadicremona/AVCP-Xml/commit/8e9084020b1081b994673b322d5ab1dcd78f85a8), ma non ho ancora fatto un rilascio perché volevo controllare ancora un paio di cose e avere qualche feedback da chi sta provando le installazioni. A questo punto, forse è meglio se faccio una nuova release.
Grazie!

**Comment by herald-si** [comment]
Si, la versione del commit l'avevo vista per l'applicativo. 
L'errore l'ho riscontrato in fase di update del database nel file:
/app/checkDbUpdate.php
riga 68: `SELECT `numero` FROM `avcp_versioni` ORDER BY `numero` DESC LIMIT 0,1`  restituisce `0.8.3` anziché la `0.8.11` (una volta aggiornato)
riga 71: il controllo non passa come da issue iniziale

Grazie per il lavoro svolto!

**Comment by ClaudioRoncaglio** [comment]
Aaaahhh! :sob: Purtroppo ha ragione. 
Risolvo la cosa e poi rilascio una versione 0.9.0 così che anche chi ha quelle vecchie la veda.
