### ISSUE TITLE
Warning in esportazione ODS

### ISSUE THREAD

**Issue by giox069** [provinciadicremona/AVCP-Xml#30]
inauguro io la lista delle issues ;)

Questa issue è presente nella versione 0.9.0 che ho appena installato, non so se è stata fixata con commit successivi.

Se da un elenco gare (es: la pagina "Elenco gare 2019") seleziono "Scarica elenco in formato ods"

Il file .ods generato contiene il seguente warning ripetuto molte volte:

**Notice**: Undefined index: chiuso in **/var/www/siti/apps/anac/app/webServices/odsUserExport.php** on line **113**

Come workaround ho temporaneamente impostato display_errors = Off in php.ini e riavviato apache, e funziona.

**Comment by ClaudioRoncaglio** [comment]
Salve, penso che abbiate avuto qualche problema durante l'aggiornamento.
Provi a controllare che la vista `avcp_export_ods` contenga il campo `chiuso` e che sia popolato.
In caso non ci sia, cancelli la vista e la ricrei con questa query:
```sql
CREATE VIEW `avcp_export_ods` AS select 
    `l`.`id` AS `id`,
    `l`.`anno` AS `anno`,
    `l`.`numAtto` AS `numAtto`,
    `l`.`cig` AS `cig`,
    `l`.`oggetto` AS `oggetto`,
    `l`.`sceltaContraente` AS `sceltaContraente`,
    `l`.`dataInizio` AS `dataInizio`,
    `l`.`dataUltimazione` AS `dataUltimazione`,
    `l`.`importoAggiudicazione` AS `importoAggiudicazione`,
    `l`.`importoSommeLiquidate` AS `importoSommeLiquidate`,
    `l`.`chiuso` AS `chiuso`,
    (SELECT COUNT(0) 
        FROM `avcp_ld` `ldl` 
        WHERE ((`l`.`id` = `ldl`.`id`) 
            AND (`ldl`.`funzione` = '01-PARTECIPANTE'))) AS `partecipanti`,
    (SELECT COUNT(0) FROM `avcp_ld` `ldl` 
        WHERE ((`l`.`id` = `ldl`.`id`) 
            AND (`ldl`.`funzione` = '02-AGGIUDICATARIO'))) AS `aggiudicatari`,
    `l`.`userins` AS `userins`,
    group_concat(`ditta`.`ragioneSociale` separator 'xxxxx') AS `nome_aggiudicatari` 
    FROM ((`avcp_lotto` `l` 
            LEFT JOIN `avcp_ld` `ld` 
            ON(((`l`.`id` = `ld`.`id`) 
                    and (`ld`.`funzione` = '02-AGGIUDICATARIO')))) 
        LEFT JOIN `avcp_ditta` `ditta` 
        ON(`ld`.`codiceFiscale` = `ditta`.`codiceFiscale`)) 
    GROUP BY `l`.`id` 
    ORDER BY `l`.`anno`,
    `l`.`id`;
```
Nel caso la vista sia a posto ma il campo "chiuso" sia vuoto, può essere che lo stesso campo manchi dalla tabella `avcp_lotto`.
In questo caso può lanciare questa query per risolvere:
```sql 
ALTER TABLE `avcp_lotto` ADD `chiuso` BOOLEAN NOT NULL DEFAULT FALSE AFTER `flag`;
```

Mi faccia sapere se riesce a risolvere.

Cordiali saluti.

**Comment by giox069** [comment]
Il campo "chiuso" mancava dalla view avcp_export_ods ma era presente nella tabella avcp_lotto, quindi ho cancellato e ricreato la view con il comando create qui sopra.

Ora il warning non appare più, grazie.

Chissà in quale upgrade si sarà perso... dal 2014 ne ho fatti più di uno.

Grazie di nuovo per l'aiuto.
