### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cprampolini** [provinciadicremona/AVCP-Xml#31]
Buongiorno,
sto facendo alcuni test e una cosa non mi torna e mi pare non corretta: 
ANAC richiede l'indicazione dei lotti comunque "movimentati" o ancora aperti nell'anno di riferimento
dell'xml.
Ho provato a inserire una gara in competenza 2018, scadenza 2020 e liquidazione parziale.
Teoricamente questo lotto dovrebbe essere inserito anche nella comunicazione 2019, ma vedo che non è così.
Sbaglio qualcosa ?

Grazie

**Comment by ClaudioRoncaglio** [comment]
Entrando con l'utente admin, può bloccare l'anno 2018 e successivamente
farne l'avanzamento. Questo porta al 2019 tutti i lotti non ancora
totalmente liquidati a meno che non esplicitamente chiusi.

Il mar 28 gen 2020, 16:51 cprampolini <notifications@github.com> ha scritto:

**Comment by cprampolini** [comment]
Grazie della risposta, ma come si fa l'avanzamento ?

**Comment by cprampolini** [comment]
Come non detto: visto ora. Grazie

**Comment by ClaudioRoncaglio** [comment]
Deve entrare come admin. Di fianco all'elenco degli anni, nella home, le
comparirà la scritta blocca. Una volta bloccato, la scritta diventerà
sblocca e di fianco ci sarà una freccia. Cliccando sulla freccia si ha
l'avanzamento.

Il mar 28 gen 2020, 17:19 cprampolini <notifications@github.com> ha scritto:
