### ISSUE TITLE
Nell' XML file sono vuoti i campi dei partecipanti e aggiudicatari

### ISSUE THREAD

**Issue by antoninomessina** [provinciadicremona/AVCP-Xml#32]
Salve, come da oggetto nell'esportazione del file XML(ma anche HTML) mancano i partecipanti e aggiudicatari di ogni singola gara. 
Ogni gara ha correttamente associati i partecipanti e gli aggiudicatari e l'XML viene validato correttamente. Cosa può essere? grazie anticipatamente

**Comment by ClaudioRoncaglio** [comment]
Qualche vista nel db non è stata creata correttamente, nello specifico
avcp_xml_ditte. Provi a cancellarla e ricrearla usando la query corretta
che trova all'interno del file avcp.sql.

Il mar 28 gen 2020, 17:49 antoninomessina <notifications@github.com> ha
scritto:

**Comment by antoninomessina** [comment]
Gentilissimo grazie ho risolto il problema!
