### ISSUE TITLE
avcp_ruolotype case sensitive

### ISSUE THREAD

**Issue by roberto2011** [provinciadicremona/AVCP-Xml#34]
Nell'importare avcp.sql in mysql 5.7 in windows (ma anche in linux) )viene creata al tabella avcp_ruolotype e non avcp_ruoloType.
Per risolvere il problema del menu "ruolo del raggruppamento", che non viene visualizzato ho modificato la riga 38 del file \app\model\dittacerca.php
 da:
$queryRuolo = "SELECT * FROM avcp_ruoloType ORDER BY sceltaContraente ASC";
a:
$queryRuolo = "SELECT * FROM avcp_ruolotype ORDER BY sceltaContraente ASC";

Saluti  e grazie per il lavoro svolto.

**Comment by ClaudioRoncaglio** [comment]
Buongiorno, sinceramente è la prima volta che sento di questo errore.
Ho controllato le query di aggiornamento e di creazione della tabella ed usano il nome corretto.
Penso che dobbiate controllare le impostazioni del vostro mysql; partendo da quanto ho letto qui:
https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html

penso che il vostro problema possa risiedere nel valore di questa variabile globale di mysql:

https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_lower_case_table_names

Provi a verificare che sia impostata correttamente.

Comunque mi sembra strano che non vi dia problemi anche con la tabella   `avcp_sceltaContraenteType`.

Una maniera migliore per risolvere il problema, comunque, penso che sia rinominare la tabella con il case corretto, così al prossimo aggiornamento non dovrete ricordarvi di rimodificare il programma.

Mi faccia sapere se riuscite a risolvere.

**Comment by roberto2011** [comment]
Modificato il db (molto più semplice e funzionale!)
RENAME TABLE avcp_ruolotype TO avcp_ruoloType ;

per la tabella avcp_sceltaContraenteType il problema non si verifica perchè la crea il php dalla funzione 
function updateTableSceltaContraente($db) 
infatti nel db mi trovo due tabelle.
avcp_sceltacontraentetype
avcp_sceltaContraenteType

Problema risolto. 
Grazie  Claudio

**Comment by ClaudioRoncaglio** [comment]
Di niente, sono contento che sia tutto a posto! :smile:
