### ISSUE TITLE
Mysqldump problem

### ISSUE THREAD

**Issue by gigithesnow** [provinciadicremona/AVCP-Xml#36]
Ciao a tutti e complimenti per il progetto. 

Avviando mysqldump del database avcp viene creato il dump della sola tabella avcp_ditta (ddl + dati). 

Descrizione per riprodurre il problema:
-Win64
- avcp ver. 0.8.11 (con i vari aggiornamenti dal 2016) 
-Mysql 5.7.16
-Utente Mysql di backup con ruolo **backupAdmin** assegnato

 il comando lanciato per avviare il dump è :

Mysqldump - - host "localhost" --user=%dbuser% --password = %pass% --single-transaction --events --routines --triggers --add-drop-table --databases avcp > avcp.sql

ERRORE : Il file viene creato ma riporta lo script per ricostruire lo schema con la sola tabella avcp_ditta. 
Nell'error log di mysql non ho trovato nulla di rilevante. 

Aggiungo infine che :
1)tale script funziona correttamente con gli altri database. 
2) questo script funziona anche con il db  avcp se avviato da un utente mysql plenipotenziario.

Nota: non so se é normale o derivi da un mio errore negli aggiornamenti di avcp, ma riscontro che le tabelle hanno diverse collation esempio:

Avcp_ditta: utf8_bin
Avcp_ld : utf8_general_ci

**Comment by ClaudioRoncaglio** [comment]
Salve, ho provato a lanciare il comando su un paio di installazioni e funziona perfettamente.
Penso che il problema risieda semplicemente nei permessi dell'utente.
A partire dalla 0.8.0, è comunque necessario garantire pieni poteri all'utente del db per consentire agli script di aggiornamento di agire liberamente.
Le consiglio di provare a rilanciare il comando per il dump dopo avergli dato tutti i grant con:
```sql
GRANT ALL ON nomeDbAvcp.* TO 'utenteAvcp'@'localhost' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
```
Per quel che riguarda le collation invece è una mia dimenticanza in fase di pulizia del codice, grazie di avermelo fatto notare così le correggo subito.

**Comment by gigithesnow** [comment]
Grazie per la risposta innanzitutto,

Mi è chiara la necessità dei diritti completi per l'utilizzo e l'aggiornamento dell'applicativo - a tal scopo ho dedicato un utente con tutti i diritti sullo schema specifico.
Per quel che riguarda il backup non vedo ragioni che richiedono i pieni poteri.

L'utente da me usato per lanciare qualsiasi backup non ha alcun privilegio specifico su db ma il privilegio globale **backupAdmin** (cfr. seguente link.) selezionato dal tab Administrative Role della scheda Users and Privileges di MySQLWorkbench 

[https://dev.mysql.com/doc/workbench/en/wb-mysql-connections-navigator-management-users-and-privileges.html#wb-users-and-privileges-accounts](url)

Le chiedo (sono nuovo su github - non so se ci sono regole di formalità :) ) l'ulteriore cortesia di verificare l'esito del mysqldump con un utente caratterizzato dal solo ruolo amministrativo di backupAdmin.

Grazie ancora.

Gigi

**Comment by ClaudioRoncaglio** [comment]
Salve,
ho guardato il manuale che avete linkato e ho trovato questo:

>  For example, if you select the role BackupAdmin, the privileges granted include EVENT, LOCK TABLES, SELECT, SHOW DATABASES

Non usando MySQLWorkbench, ho creato un utente con quei privilegi  (che ho chiamato backupper) e ho provato a lanciare mysqldump; questo è l'errore che mi restituisce: 

```bash
mysqldump: Couldn't execute 'show create table `avcp_export_ods`': SHOW VIEW command denied to user 'backupper'@'localhost' for table 'avcp_export_ods'
```
Ed aprendo il file generato, si interrompe dopo la `INSERT` di `avcp_ditta`.
In effetti `SHOW VIEW` non è tra i privilegi assegnati.

Dopo averlo aggiunto ai privilegi del mio utente, il comando funziona correttamente e genera un file di backup uguale a quello che ottengo usando gli altri utenti.

```bash
-rw-r--r-- 1 claudio claudio 25653 mar 27 11:33 avcp-avcp.sql
-rw-r--r-- 1 claudio claudio 25653 mar 30 09:50 avcp-backupper.sql
-rw-r--r-- 1 claudio claudio 25653 mar 30 09:39 avcp-claudio.sql
```
Spero che questo vi risolva il problema.
Cordiali saluti.

**Comment by gigithesnow** [comment]
Chiarissimo,
Come immaginavo l'ipotetica issue si è rivelata essere un mio errore da dbadmin (tra le altre cose, non vedevo l'errore sui grant a causa dell'opzione --no-beep attiva sul file di configurazione).

Adesso il mio utente backupparo globale ha i privilegi su EVENT, LOCK TABLES, SELECT, SHOW DATABASES e SHOW VIEW.

Grazie ancora.

**Comment by ClaudioRoncaglio** [comment]
Di niente, son felice che abbia risolto!

Il mar 31 mar 2020, 17:57 gigithesnow <notifications@github.com> ha scritto:
