### ISSUE TITLE
Richiesta di inserimento di nome e codiceIPA del proprio Ente nel file publiccode.yml

### ISSUE THREAD

**Issue by cedLegnago** [provinciadicremona/AVCP-Xml#40]
Si Richiede di inserire gentilmente il comune di Legnago fra gli utilizzatori del vostro applicativo, secondo quanto indicato in https://developers.italia.it/it/riuso/dichiarazione 

C_E512
Comune di Legnago

**Comment by ClaudioRoncaglio** [comment]
Fatto, grazie per la segnalazione
