### ISSUE TITLE
Ric

### ISSUE THREAD

**Issue by Nestore74** [provinciadicremona/AVCP-Xml#42]
Si Richiede di inserire gentilmente il comune di Berceto fra gli utilizzatori del vostro applicativo, secondo quanto indicato in https://developers.italia.it/it/riuso/dichiarazione

c_a788
Comune di Berceto

Grazie per la collaborazione

**Comment by ProvinciaCremona** [comment]
Salve, 
ho inserito il comune di Berceto come richiesto. 

Grazie per la segnalazione e cordiali saluti. 

----------------------------------------- 
Claudio Roncaglio 
Sistemi Informativi 
della Provincia di Cremona 
C.so Vittorio Emanuele II,17 
tel. +39 0372 406247 fax +39 0372 406301 
----------------------------------------- 


Da: "Nestore74" ***@***.***> 
A: "provinciadicremona" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Inviato: Martedì, 24 gennaio 2023 11:37:52 
Oggetto: [provinciadicremona/AVCP-Xml] Ric (Issue #42) 





Si Richiede di inserire gentilmente il comune di Berceto fra gli utilizzatori del vostro applicativo, secondo quanto indicato in [ https://developers.italia.it/it/riuso/dichiarazione | https://developers.italia.it/it/riuso/dichiarazione ] 


c_a788 
Comune di Berceto 

Grazie per la collaborazione
