### ISSUE TITLE
[BUG] AGGIUNTA GARE

### ISSUE THREAD

**Issue by pnatale** [provinciadicremona/AVCP-Xml#43]
Salve, ho un problema con l'aggiunta delle gare, quando clicco su inserisci gara vedo uno schermo bianco.
Se faccio importa gara, non mi da nessun errore importando il csv ma mi dice gare inserite: -1.

Come posso fare?

**Comment by pnatale** [comment]
Credo di aver risolto, implementando il database..
Solo una domanda, quali sono i valori accettati per la validazione nel campo sommeAggiudicazione e importoLiquidato?

**Comment by ProvinciaCremona** [comment]
Nessun tipo di valore in particolare, può anche essere lasciato vuoto ed in questo caso viene popolato a 0.00. 
Dev'essere un numero con al massimo due decimali ed il punto come separatore, ma il programma accetta anche la virgola convertendola. 

Cordiali saluti. 

----------------------------------------- 
Claudio Roncaglio 
Sistemi Informativi 
della Provincia di Cremona 
C.so Vittorio Emanuele II,17 
tel. +39 0372 406247 fax +39 0372 406301 
----------------------------------------- 


Da: "Pietro Natale" ***@***.***> 
A: "provinciadicremona" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Inviato: Sabato, 28 gennaio 2023 11:35:35 
Oggetto: Re: [provinciadicremona/AVCP-Xml] [BUG] AGGIUNTA GARE (Issue #43) 





Credo di aver risolto, implementando il database.. 
Solo una domanda, quali sono i valori accettati per la validazione nel campo sommeAggiudicazione e importoLiquidato?

**Comment by pnatale** [comment]
Purtroppo, inserendolo vuoto o con 0.00 mi da errore nella validazione

**Comment by ClaudioRoncaglio** [comment]
Ho provato sia lasciando il campo aggiudicazione vuoto, sia mettendo 0.00 e in entrambi i casi il programma genera un xml valido. Che messaggio di errore le appare quando tenta di validare? Provi la validazione con sorgente che le consente di vedere anche il codice.

**Comment by pnatale** [comment]
Mi dice appunto che c'è l'errore alla riga xxx.
Dove va a vedere che il valore visionato sia quando inserisco 0 che lascio vuoto, mi risulta sempre come zero nell'xml

**Comment by ClaudioRoncaglio** [comment]
Non riesco a replicare il suo errore in nessun modo: potrebbe incollarmi il messaggio di errore che ottiene tentando di validare il file?

PS: sta usando la versione 0.9.2?
