### ISSUE TITLE
[BUG]Lista elenco gare

### ISSUE THREAD

**Issue by Manuelmagnani** [provinciadicremona/AVCP-Xml#44]
Ciao, anzitutto grazie mille per il software.
Quando entro in elenco gare per vedere quelle inserite mi dice Totale inserite: 288
ma me ne fa vedere una sola evidenziata in verde fino a Imp. Agg.
ho la versione AVCP Xml - versione 0.9.2
Grazie mille
Manuel

**Comment by Manuelmagnani** [comment]
ho risolto modificando il file garaElenca.php sotto app view
da
<td><?php stampaValuta($out[$x]['importoAggiudicazione']);?></td>
 <td><?php stampaValuta($out[$x]['importoSommeLiquidate']);?></td>
a
 <td><?php echo($out[$x]['importoAggiudicazione']);?></td>
<td><?php echo($out[$x]['importoSommeLiquidate']);?></td>

**Comment by ClaudioRoncaglio** [comment]
Salve, nel branch master ho corretto l'errore. 
Se vuole può sostituire la funzione stampaValuta che trova nel file app/functions.php con quella che le incollo qua sotto, 
così potrà avere anche i separatori di migliaia e dei decimali corretti.
Grazie per la segnalazione :+1: 

```
/**
 *
 * @param string $importo        
 * @return string
 */
function stampaValuta($val) {
    if (php_uname('s') === 'Linux' && PHP_MAJOR_VERSION < 8 ) {
            echo strtr(money_format('%.2n', $val), 'EUR', '€');
    } else {
        echo '€ '.number_format($val, 2, ',', '.');
    }
}

```
