### ISSUE TITLE
[BUG] Errore visualizzazione gare con PHP 8.2

### ISSUE THREAD

**Issue by StefanoPerinetti** [provinciadicremona/AVCP-Xml#46]
**Descrivi il bug**
Le gare non vengono visualizzate

**Come riprodurlo:**
Utilizzare il software con PHP 8.2 o superiore (Non ho provato ma credo sia un problema che si introduce con php 8 o superiore)
Con php 7.4 o inferiore funziona correttamente.

**Screenshots**
Se possibile, aggiungi degli screenshot per mostrarci meglio il bug.

**Informazioni sull'installazione del programma AVCP-Xml:**
 - Versione di AVCP-Xml [v. 0.9.2]
 - Sistema Operativo: [Debian Gnu Linux ]
 - Versione web server  [nginx/1.21.4]
 - Versione di MySQL [mysqld 8.0.27-18]
 - Versione di PHP [8.2]
 - Browser [tutti]

**Aggiungi il log degli errori**
 PHP Fatal error: Uncaught Error: Call to undefined function money_format() in /home/artaabruzzo-avcp/htdocs/avcp.artaabruzzo.local/app/functions.php:23

**Comment by ProvinciaCremona** [comment]
Salve, 
siamo a conoscenza del problema, in attesa del rilascio della nuova release del programma, sostituisca il file functions.php che le allego con quello presente nella cartella 'app/'. 
Risolverà il problema. 

Cordiali saluti e grazie per la segnalazione. 



----------------------------------------- 
Claudio Roncaglio 
Sistemi Informativi 
della Provincia di Cremona 
C.so Vittorio Emanuele II,17 
tel. +39 0372 406247 fax +39 0372 406301 
----------------------------------------- 


Da: "StefanoPerinetti" ***@***.***> 
A: "provinciadicremona" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Inviato: Venerdì, 15 dicembre 2023 10:04:59 
Oggetto: [provinciadicremona/AVCP-Xml] [BUG] Errore visualizzazione gare con PHP 8.2 (Issue #46) 





Descrivi il bug 
Le gare non vengono visualizzate 

Come riprodurlo: 
Utilizzare il software con PHP 8.2 o superiore (Non ho provato ma credo sia un problema che si introduce con php 8 o superiore) 
Con php 7.4 o inferiore funziona correttamente. 

Screenshots 
Se possibile, aggiungi degli screenshot per mostrarci meglio il bug. 

Informazioni sull'installazione del programma AVCP-Xml: 

    * Versione di AVCP-Xml [v. 0.9.2] 
    * Sistema Operativo: [Debian Gnu Linux ] 
    * Versione web server [nginx/1.21.4] 
    * Versione di MySQL [mysqld 8.0.27-18] 
    * Versione di PHP [8.2] 
    * Browser [tutti] 


Aggiungi il log degli errori 
PHP Fatal error: Uncaught Error: Call to undefined function money_format() in /home/artaabruzzo-avcp/htdocs/avcp.artaabruzzo.local/app/functions.php:23
