### ISSUE TITLE
Modifiche in mysql server per funzionamento con date non valide

### ISSUE THREAD

**Issue by frenier** [provinciadicremona/AVCP-Xml#7]
CIao,
nell'installare la procedura su un server ubuntu 16.04 LTS con mysql 5.7.22 ho riscontrato che la procedura non agganciava il db correttamente per una caratteristica nell'installazione standard introdotta in mysql (da come ho capito dalla versione 5.6) che non accetta date 0000-00-00 ritenendola non valida.
Infatti il default SQL mode in MySQL 5.7 include : ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, and NO_ENGINE_SUBSTITUTION
Per poter operare con le date 0000-00-00 ho eliminato lo il modo STRICT_TRANS_TABLES.
La modifica nel caso di ubuntu è da effettuare in /etc/mysql/mysql.conf.d/mysqld.cnf
aggiungendo la stringa
sql_mode="ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
e riavviando il servizio mysql

**Comment by ProvinciaCremona** [comment]
Innanzitutto grazie mille per i contributi! 

Questo delle date però è un bel problema perché la maggior parte degli utenti del programma non sono tecnici e lo fanno girare su xampp. 

Devo accertarmi che non sia possibile aggirare il problema senza fargli mettere manno ai file di configurazione (capacissimi di aprirli con word). 



----------------------------------------- 
Claudio Roncaglio 
Ufficio per le Relazioni con il Pubblico 
della Provincia di Cremona 
C.so Vittorio Emanuele II,17 
tel. +39 0372 406247 fax +39 0372 406301 
----------------------------------------- 


Da: "frenier" <notifications@github.com> 
A: "proviniciacremona/AVCP-Xml" <AVCP-Xml@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Inviato: Mercoledì, 2 maggio 2018 21:56:02 
Oggetto: [proviniciacremona/AVCP-Xml] Modifiche in mysql server per funzionamento con date non valide (#7) 



CIao, 
nell'installare la procedura su un server ubuntu 16.04 LTS con mysql 5.7.22 ho riscontrato che la procedura non agganciava il db correttamente per una caratteristica nell'installazione standard introdotta in mysql (da come ho capito dalla versione 5.6) che non accetta date 0000-00-00 ritenendola non valida. 
Infatti il default SQL mode in MySQL 5.7 include : ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, and NO_ENGINE_SUBSTITUTION 
Per poter operare con le date 0000-00-00 ho eliminato lo il modo STRICT_TRANS_TABLES. 
La modifica nel caso di ubuntu è da effettuare in /etc/mysql/mysql.conf.d/mysqld.cnf 
aggiungendo la stringa 
sql_mode="ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" 
e riavviando il servizio mysql

**Comment by dgardina** [comment]
Ho avuto un problema simile dopo la migrazione su un nuovo server con PHP7 e MYSQL8 (è dovuto al sql_mode "NO_ZERO_DATE").. Ho risolto nello stesso modo, seguendo anche le indicazioni dei seguenti link:
1) https://stackoverflow.com/questions/36374335/error-in-mysql-when-setting-default-value-for-date-or-datetime
2) https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date
3) https://kevdees.com/disable-mysql-strict-mode-and-no_zero_date-errors-in-homestead/

**Comment by ClaudioRoncaglio** [comment]
Bel guaio perché considerando l'utenza non posso richiederle di intervenire sulle impostazioni del server.
Dopo la sua segnalazione ho creato una soluzione alternativa che gestisce l'inserimento di un valore NULL nei campi data: la sto testando sul mio pc e funziona ;-) 

Cercherò di fare qualche ulteriore prova e la inserirò nel nuovo rilascio.
